### ISSUE TITLE
Code won't exit

### ISSUE THREAD

**Issue by GForceSquared** [pootle/pisteppers#2]
So after playing around with the motors, I realized that the code would never exit. I would get something like :
> stepper control.Yaxis: action >enable< complete: disable.
stepper control.Xaxis: action >enable< complete: disable.
stepper control: action >wavepulsemaker< complete: all done in 1 waves.

After that though, the code would never exit. How can I solve this issue?

**Comment by GForceSquared** [comment]
I hope you got this question because I am effectively stuck at this point as I cannot figure this part out. Thanks for your time.

**Comment by pootle** [comment]
Sorry, missed the notification for this. Because this was only a test program run from command prompt, I usually just exit by using ctrl-C. I'll have a quick look and see if there might be a better way....

**Comment by pootle** [comment]
There was already a shutdown in the motor driving thread, but nothing to call it from the command line interface class. I've added an exit() method to the clif class, so now you can cleanly shut down the threads (when the motors are idle) by clif.exit() (or equivalent in your own control class)

**Comment by GForceSquared** [comment]
Ok thanks, it works now!
