### ISSUE TITLE
New Raspberry Pi 3 B+ issues

### ISSUE THREAD

**Issue by GForceSquared** [pootle/pisteppers#3]
I got a new raspberry pi 3 B+ and so I loaded a clean raspbian os on a sd card and I went to download your program again. This time, however, when I ran my code that moves two stepper motor that worked before, I get this message now: 

>  wave: 12000, seconds per wave: 1800.000000, control blocks per wave: 25016.
wrappedCall: <class 'AssertionError'> exception in called code - 
File "/home/pi/pisteppers/stepwavetest.py", line 113, in wrappedRunMethod
    meth(**kwargs)
  File "/home/pi/pisteppers/stepwavetest.py", line 377, in wavepulsemaker
    assert paramset['motor'] in self.motors
stepper control: action >run agent< failed: "done" cannot finish - wavepulsemaker.

The motors don't move anymore. I'm not sure if the new board is the issue. Any help would be appreciated

**Comment by pootle** [comment]
Is the pigpio daemon running?

If it is then something has gone wrong with the setup / definition of the motors.

The self.motors in 377 is a dict which should have 1 entry per motor (the name of the motor), but it's not finding an entry with the right name, it looks like the setup failed. Are there no earlier messages?

**Comment by GForceSquared** [comment]
I had the daemon running and here is the earlier messages of the motor

> stepper control.RA: action >setup< started: .
stepper control.RA: action >pins mode set< complete: output.
stepper control.RA: action >enable< complete: disable.
stepper control.DEC: action >setup< started: .
stepper control.DEC: action >pins mode set< complete: output.
stepper control.DEC: action >enable< complete: disable.
wrapped call got exception ><class 'AssertionError'><
stepper control: action >run agent< started: wave agent: wave limits, pulses per wave: 12000, seconds per wave: 1800.000000, control blocks per wave: 25016.

Thank you for your quick response

**Comment by pootle** [comment]
I'm a bit baffled by this. Can you post the whole console log please?

**Comment by GForceSquared** [comment]
OK

> ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835_alsa.pcm.front.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM front
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835_alsa.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround21
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835_alsa.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround21
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835_alsa.pcm.surround40.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround40
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835_alsa.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround41
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835_alsa.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround50
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835_alsa.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround51
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835_alsa.pcm.surround71.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround71
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835_alsa.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM iec958
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835_alsa.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM spdif
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835_alsa.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM spdif
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'defaults.bluealsa.device'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4996:(snd_config_expand) Args evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM bluealsa
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'defaults.bluealsa.device'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4996:(snd_config_expand) Args evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM bluealsa
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
B
2
A
1
Going Right not Left for 1 inch(es)
Going Up not Down for 1 inch(es)
stepper control.RA: action >setup< started: .
stepper control.RA: action >pins mode set< complete: output.
stepper control.RA: action >enable< complete: disable.
stepper control.DEC: action >setup< started: .
stepper control.DEC: action >pins mode set< complete: output.
stepper control.DEC: action >enable< complete: disable.
wrapped call got exception ><class 'AssertionError'><
stepper control: action >run agent< started: wave agent: wave limits, pulses per wave: 12000, seconds per wave: 1800.000000, control blocks per wave: 25016.
wrappedCall: <class 'AssertionError'> exception in called code - 
File "/home/pi/pisteppers/stepwavetest.py", line 113, in wrappedRunMethod
    meth(**kwargs)
File "/home/pi/pisteppers/stepwavetest.py", line 377, in wavepulsemaker
    assert paramset['motor'] in self.motors
stepper control: action >run agent< failed: "done" cannot finish - wavepulsemaker.

**Comment by pootle** [comment]
Still confused, do you have a separate python module calling things in stepwavetest.py, or have you edited stepwavetest.py? Can you post any new / changed files you are using here?

**Comment by GForceSquared** [comment]
I have a separate program that imports stepwavetest.py and uses its code

> clif=st.makeagents()
m1p={'motor':'Xaxis', 'startsr':100, 'maxsr':1000, 'overreach':1.1, 'ramp':1, 'totalsteps':moveX, 'pulseontime':2, 'forward':locationX,'warp':2}
m2p={'motor':'Yaxis', 'startsr':100, 'maxsr':1000, 'overreach':1.1, 'ramp':1, 'totalsteps':moveY, 'pulseontime':2, 'forward':locationY,'warp':2}
#clif.runmotors((m1p,))
#clif.runmotors((m2p,))
clif.runmotors((m1p, m2p))
clif.exit()

**Comment by pootle** [comment]
Ah! ok, I thought it was something like this!
makeagents names the motors 'RA' and 'DEC' (if you haven't edited it), but your call to runmotors uses the names 'Xaxis' and 'Yaxis'. The failure seems to be because the name in the onewave constructor call:
`    sa = onewave(inq=cmdq, outq=respq, motors=(
          {'name':'RA',  'loglevel':7, 'pins':{'enable':21, 'direction': 12, 'step': 13, 'steplevels': (20,19,16)}}
        , {'name':'DEC', 'loglevel':7, 'pins':{'enable':25, 'direction': 18, 'step': 27, 'steplevels': (24,23,22)}}))
`
doesn't match the name set in m1p or m2p when you call runmotors.

**Comment by GForceSquared** [comment]
Ok thanks so much! I will try this out as soon as possible!
