### ISSUE TITLE
More documentation please

### ISSUE THREAD

**Issue by Farmertatata** [pootle/pisteppers#6]
Hi,
I tried this stepper driver with a single ULN-type stepper motor, and it worked great.
However I could not understand how to operate multiple motors simultaneously with this driver.
I think more documentation for the Wiki will be very helpful for many who intends to create their original robots.
Could you kindly consider to add some explanations to the multiple motors?
Thanks,

**Comment by pootle** [comment]
I'm working on a new heavily modified version, but only for 1 motor so far, so I'm not updating the docs for this version, but if you can explain your difficulty I'll try and help in the meantime.

Are you using the web interface, or just using the other mmodules directly?

**Comment by Farmertatata** [comment]
Thank you for your reply.
I used the web interface for 1 motor control. It was easy to use.
As a next step, I want to operate 4 motors at the same time (I don't know whether it's possible or not though).
In my understanding, there are some modules that mentions to the multi-motor operation, and I have to write some programs that call the appropriate modules, because they are not able to use with the web app.
However I cannot understand which module I have to use because there are many modules in the repository and I'm a beginner of the python coding (I cannot read the codes well).
Simple commands are enough for helping my understanding.
I'll appreciate if you could give me a time... but I can wait for your next heavy modifications.
Thanks!

**Comment by Farmertatata** [comment]
Now I finally noticed that everything was written in the Quickstart guide.
The only thing I had to do is copy & paste the motor classes in the .json file and config file, and rename them.
motorpair8825.json file was a good example for that purpose...
How a nice structure this is!
I'm ashamed of me. Close this session.
